### ISSUE TITLE
Add function for emfatic tool diagram rendering

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/platformtools#21]
There is no function to handle the rendering of emfactic diagrams one should be added so that emfatic diagrams can be visualised using a render diagram buttob.

**Comment by szschaler** [comment]
Thanks for raising this as an issue. Isn't there functionality for this already in the Epsilon Playground? Shouldn't we be able to port that to the MDENet education platform?

**Comment by szschaler** [comment]
Related to https://github.com/mdenet/educationplatform/issues/110
