### ISSUE TITLE
Xtext tool doesn't report back editor-generation errors

### ISSUE THREAD

**Issue by szschaler** [mdenet/platformtools#39]
When something goes wrong when generating an editor from the Xtext tool, the student cannot see the Xtext error message because this isn't reported back to the platform. Instead, all they see is a generic error message that there was an issue generating the editor.

**Comment by barnettwilliam** [comment]
@szschaler  does the included support in commit e3f041d1ea2e3bc850a54aafa196e6b2da8aa3e5  for displaying stderr in the log resolve this? or is something more required here?

Could you provide an example of the kind of error in the Xtext activity file that isn't seen?

**Comment by szschaler** [comment]
Sorry, haven't had time to check myself yet. Anything where the grammar isn't valid would be relevant here. For example, a grammar that defines a top rule, but then references an empty rule:

```
TopRule:
  elements += Element*
;

Element:
  'element' 
;
```

This should produce an error message from the generation process so that the student can work out what went wrong.
