### ISSUE TITLE
Xtext tool scheduled shutdown tool config webserver offline

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/platformtools#44]
Following a scheduled shutdown introduced by PR https://github.com/mdenet/platformtools/pull/34rmtools/pull/34 for resource management, the Xtext tool files go offline and are not accessible causing activities that use it to display an indicating the tool config is unavailable.

Using command`touch /usr/local/webapps/tomcat/ROOT.war` in the running Xtext tool container causes the toolservice webserver to be re-deployed and the tool configuration to be available.

**Comment by szschaler** [comment]
Is this standard tomcat behaviour?

**Comment by barnettwilliam** [comment]
It could be, I will check the deployOnStartup setting.

**Comment by barnettwilliam** [comment]
It seems to be the expected behaviour based on tomcat documentation [here](https://tomcat.apache.org/tomcat-9.0-doc/config/host.html#Automatic_Application_Deployment).

The `start.sh` isn't deleting the root app's deployed directory so tomcat thinks it's deployed. The fix it to delete this directory.
